MOCK_GAMES = [
            {
                "game_id": "mock-001",
                "home_team": "Lakers",
                "away_team": "Warriors",
                "home_score": 145,
                "away_score": 108,
                "home_record": "28-16",
                "away_record": "26-18",
                "status": "Final",
            },
            {
                "game_id": "mock-002",
                "home_team": "Celtics",
                "away_team": "Heat",
                "home_score": 101,
                "away_score": 99,
                "home_record": "30-15",
                "away_record": "24-21",
                "status": "Q4 2:31",
            },
            {
                "game_id": "mock-003",
                "home_team": "Bucks",
                "away_team": "76ers",
                "home_score": 87,
                "away_score": 92,
                "home_record": "18-25",
                "away_record": "27-19",
                "status": "Q3 7:44",
            },
            {
                "game_id": "mock-004",
                "home_team": "Nuggets",
                "away_team": "Suns",
                "home_score": 55,
                "away_score": 58,
                "home_record": "30-15",
                "away_record": "27-18",
                "status": "Halftime",
            },
            {
                "game_id": "mock-005",
                "home_team": "Knicks",
                "away_team": "Nets",
                "home_score": 91,
                "away_score": 61,
                "home_record": "25-20",
                "away_record": "12-31",
                "status": "Q2 1:18",
            },
            {
                "game_id": "mock-006",
                "home_team": "Mavericks",
                "away_team": "Clippers",
                "home_score": 120,
                "away_score": 117,
                "home_record": "26-19",
                "away_record": "24-21",
                "status": "Final",
            },
            {
                "game_id": "mock-007",
                "home_team": "Kings",
                "away_team": "Grizzlies",
                "home_score": 89,
                "away_score": 94,
                "home_record": "12-34",
                "away_record": "18-25",
                "status": "Q4 9:02",
            },
            {
                "game_id": "mock-008",
                "home_team": "Raptors",
                "away_team": "Bulls",
                "home_score": 73,
                "away_score": 70,
                "home_record": "27-19",
                "away_record": "22-25",
                "status": "Q3 3:55",
            },
            {
                "game_id": "mock-009",
                "home_team": "Pelicans",
                "away_team": "Thunder",
                "home_score": 98,
                "away_score": 102,
                "home_record": "11-36",
                "away_record": "37-9",
                "status": "Final",
            },
        ]