export const mockProps = [
  {
    player: "Stephen Curry",
    team: "GSW",
    opponent: "LAL",
    projected: { pts: 31.2, reb: 5.1, ast: 6.7 },
    onFloor: true,
    game: { teamScore: 94, oppScore: 99, quarter: "3rd", clock: "9:41" },
  },
  {
    player: "Klay Thompson",
    team: "GSW",
    opponent: "LAL",
    projected: { pts: 21.4, reb: 3.8, ast: 2.5 },
    onFloor: true,
    game: { teamScore: 94, oppScore: 99, quarter: "3rd", clock: "9:41" },
  },
  {
    player: "Draymond Green",
    team: "GSW",
    opponent: "LAL",
    projected: { pts: 9.6, reb: 8.4, ast: 7.3 },
    onFloor: false,
    game: { teamScore: 94, oppScore: 99, quarter: "3rd", clock: "9:41" },
  },
  {
    player: "Andrew Wiggins",
    team: "GSW",
    opponent: "LAL",
    projected: { pts: 17.9, reb: 4.6, ast: 2.1 },
    onFloor: true,
    game: { teamScore: 94, oppScore: 99, quarter: "3rd", clock: "9:41" },
  },
  {
    player: "Chris Paul",
    team: "GSW",
    opponent: "LAL",
    projected: { pts: 12.3, reb: 4.1, ast: 8.8 },
    onFloor: false,
    game: { teamScore: 94, oppScore: 99, quarter: "3rd", clock: "9:41" },
  },
  {
    player: "LeBron James",
    team: "LAL",
    opponent: "GSW",
    projected: { pts: 27.4, reb: 7.9, ast: 8.2 },
    onFloor: true,
    game: { teamScore: 99, oppScore: 94, quarter: "3rd", clock: "9:41" },
  },
  {
    player: "Anthony Davis",
    team: "LAL",
    opponent: "GSW",
    projected: { pts: 24.1, reb: 12.3, ast: 3.1 },
    onFloor: true,
    game: { teamScore: 99, oppScore: 94, quarter: "3rd", clock: "9:41" },
  },
  {
    player: "D'Angelo Russell",
    team: "LAL",
    opponent: "GSW",
    projected: { pts: 18.7, reb: 3.4, ast: 6.0 },
    onFloor: false,
    game: { teamScore: 99, oppScore: 94, quarter: "3rd", clock: "9:41" },
  },
  {
    player: "Austin Reaves",
    team: "LAL",
    opponent: "GSW",
    projected: { pts: 15.2, reb: 4.9, ast: 4.4 },
    onFloor: true,
    game: { teamScore: 99, oppScore: 94, quarter: "3rd", clock: "9:41" },
  },
];
