export const mockProps = [
  {
    player: "Stephen Curry",
    team: "GSW",
    opponent: "LAL",
    prop: { type: "PTS", line: 27.5, overUnder: "O/U" },
    hitChance: 1.00,
    game: { teamScore: 94, oppScore: 99, quarter: "3rd", clock: "9:41" },
    current: { value: 30, label: "PTS" },
  },
  {
    player: "Nikola Jokic",
    team: "DEN",
    opponent: "PHX",
    prop: { type: "AST", line: 9.5, overUnder: "O/U" },
    hitChance: 0.84,
    game: { teamScore: 88, oppScore: 86, quarter: "3rd", clock: "6:18" },
    current: { value: 7, label: "AST" },
  },
  {
    player: "Giannis Antetokounmpo",
    team: "MIL",
    opponent: "CHI",
    prop: { type: "REB", line: 11.5, overUnder: "O/U" },
    hitChance: 0.76,
    game: { teamScore: 63, oppScore: 58, quarter: "2nd", clock: "8:27" },
    current: { value: 10, label: "REB" },
  },
  {
    player: "Tyrese Haliburton",
    team: "IND",
    opponent: "NYK",
    prop: { type: "AST", line: 10.5, overUnder: "O/U" },
    hitChance: 0.88,
    game: { teamScore: 79, oppScore: 83, quarter: "3rd", clock: "3:55" },
    current: { value: 8, label: "AST" },
  },
  {
    player: "Shai Gilgeous-Alexander",
    team: "OKC",
    opponent: "MIN",
    prop: { type: "PTS", line: 30.5, overUnder: "O/U" },
    hitChance: 0.73,
    game: { teamScore: 101, oppScore: 97, quarter: "4th", clock: "7:12" },
    current: { value: 27, label: "PTS" },
  },
  {
    player: "LeBron James",
    team: "LAL",
    opponent: "GSW",
    prop: { type: "REB", line: 8.5, overUnder: "O/U" },
    hitChance: 0.62,
    game: { teamScore: 99, oppScore: 94, quarter: "3rd", clock: "9:41" },
    current: { value: 6, label: "REB" },
  },
  {
    player: "Jayson Tatum",
    team: "BOS",
    opponent: "MIA",
    prop: { type: "PTS", line: 29.5, overUnder: "O/U" },
    hitChance: 0.54,
    game: { teamScore: 74, oppScore: 76, quarter: "2nd", clock: "1:44" },
    current: { value: 16, label: "PTS" },
  },
  {
    player: "Luka Doncic",
    team: "DAL",
    opponent: "SAC",
    prop: { type: "AST", line: 8.5, overUnder: "O/U" },
    hitChance: 0.48,
    game: { teamScore: 69, oppScore: 71, quarter: "2nd", clock: "4:33" },
    current: { value: 5, label: "AST" },
  },
  {
    player: "Devin Booker",
    team: "PHX",
    opponent: "DEN",
    prop: { type: "PTS", line: 26.5, overUnder: "O/U" },
    hitChance: 0.35,
    game: { teamScore: 86, oppScore: 88, quarter: "3rd", clock: "6:18" },
    current: { value: 13, label: "PTS" },
  },
  {
    player: "Anthony Davis",
    team: "LAL",
    opponent: "GSW",
    prop: { type: "REB", line: 12.5, overUnder: "O/U" },
    hitChance: 0.27,
    game: { teamScore: 99, oppScore: 94, quarter: "3rd", clock: "9:41" },
    current: { value: 9, label: "REB" },
  },
  {
    player: "Ja Morant",
    team: "MEM",
    opponent: "HOU",
    prop: { type: "PTS", line: 28.5, overUnder: "O/U" },
    hitChance: 0.19,
    game: { teamScore: 62, oppScore: 70, quarter: "2nd", clock: "7:09" },
    current: { value: 11, label: "PTS" },
  },
  {
    player: "Domantas Sabonis",
    team: "SAC",
    opponent: "DAL",
    prop: { type: "AST", line: 7.5, overUnder: "O/U" },
    hitChance: 0.12,
    game: { teamScore: 71, oppScore: 69, quarter: "2nd", clock: "4:33" },
    current: { value: 2, label: "AST" },
  },
];