import type { Game } from "../types";

const nil = null;

function mockGame(overrides: Partial<Game>): Game {
  return {
    game_id: "mock",
    status: "",
    home_team: "",
    home_city: "",
    home_abbreviation: "",
    home_wins: 0,
    home_losses: 0,
    home_score: 0,
    home_q1: nil,
    home_q2: nil,
    home_q3: nil,
    home_q4: nil,
    home_leader_pts_name: nil,
    home_leader_pts_val: nil,
    home_leader_reb_name: nil,
    home_leader_reb_val: nil,
    home_leader_ast_name: nil,
    home_leader_ast_val: nil,
    home_reb: nil,
    home_ast: nil,
    home_fga: nil,
    home_fgm: nil,
    home_fta: nil,
    home_ftm: nil,
    home_points: nil,
    home_3pa: nil,
    home_3pm: nil,
    away_team: "",
    away_city: "",
    away_abbreviation: "",
    away_wins: 0,
    away_losses: 0,
    away_score: 0,
    away_q1: nil,
    away_q2: nil,
    away_q3: nil,
    away_q4: nil,
    away_leader_pts_name: nil,
    away_leader_pts_val: nil,
    away_leader_reb_name: nil,
    away_leader_reb_val: nil,
    away_leader_ast_name: nil,
    away_leader_ast_val: nil,
    away_reb: nil,
    away_ast: nil,
    away_fga: nil,
    away_fgm: nil,
    away_fta: nil,
    away_ftm: nil,
    away_points: nil,
    away_3pa: nil,
    away_3pm: nil,
    ...overrides,
  };
}

export const mockGames: Game[] = [
  mockGame({
    game_id: "mock-001",
    home_team: "Lakers",
    away_team: "Warriors",
    home_city: "Los Angeles",
    away_city: "Golden State",
    home_abbreviation: "LAL",
    away_abbreviation: "GSW",
    home_wins: 28,
    home_losses: 16,
    away_wins: 26,
    away_losses: 18,
    home_score: 145,
    away_score: 108,
    status: "Final",
    home_win_prob: 100,
    away_win_prob: 0,
  }),
  mockGame({
    game_id: "mock-002",
    home_team: "Celtics",
    away_team: "Heat",
    home_city: "Boston",
    away_city: "Miami",
    home_abbreviation: "BOS",
    away_abbreviation: "MIA",
    home_wins: 30,
    home_losses: 15,
    away_wins: 24,
    away_losses: 21,
    home_score: 101,
    away_score: 99,
    status: "Q4 2:31",
    home_win_prob: 68,
    away_win_prob: 32,
  }),
  mockGame({
    game_id: "mock-003",
    home_team: "Bucks",
    away_team: "76ers",
    home_city: "Milwaukee",
    away_city: "Philadelphia",
    home_abbreviation: "MIL",
    away_abbreviation: "PHI",
    home_wins: 18,
    home_losses: 25,
    away_wins: 27,
    away_losses: 19,
    home_score: 87,
    away_score: 92,
    status: "Q3 7:44",
    home_win_prob: 55,
    away_win_prob: 45,
  }),
  mockGame({
    game_id: "mock-004",
    home_team: "Nuggets",
    away_team: "Suns",
    home_city: "Denver",
    away_city: "Phoenix",
    home_abbreviation: "DEN",
    away_abbreviation: "PHX",
    home_wins: 30,
    home_losses: 15,
    away_wins: 27,
    away_losses: 18,
    home_score: 55,
    away_score: 58,
    status: "Halftime",
    home_win_prob: 62,
    away_win_prob: 38,
  }),
  mockGame({
    game_id: "mock-005",
    home_team: "Knicks",
    away_team: "Nets",
    home_city: "New York",
    away_city: "Brooklyn",
    home_abbreviation: "NYK",
    away_abbreviation: "BKN",
    home_wins: 25,
    home_losses: 20,
    away_wins: 12,
    away_losses: 31,
    home_score: 91,
    away_score: 61,
    status: "Q2 1:18",
    home_win_prob: 82,
    away_win_prob: 18,
  }),
  mockGame({
    game_id: "mock-006",
    home_team: "Mavericks",
    away_team: "Clippers",
    home_city: "Dallas",
    away_city: "LA",
    home_abbreviation: "DAL",
    away_abbreviation: "LAC",
    home_wins: 26,
    home_losses: 19,
    away_wins: 24,
    away_losses: 21,
    home_score: 120,
    away_score: 117,
    status: "Final",
    home_win_prob: 71,
    away_win_prob: 29,
  }),
  mockGame({
    game_id: "mock-007",
    home_team: "Kings",
    away_team: "Grizzlies",
    home_city: "Sacramento",
    away_city: "Memphis",
    home_abbreviation: "SAC",
    away_abbreviation: "MEM",
    home_wins: 12,
    home_losses: 34,
    away_wins: 18,
    away_losses: 25,
    home_score: 89,
    away_score: 94,
    status: "Q4 9:02",
    home_win_prob: 45,
    away_win_prob: 55,
  }),
  mockGame({
    game_id: "mock-008",
    home_team: "Raptors",
    away_team: "Bulls",
    home_city: "Toronto",
    away_city: "Chicago",
    home_abbreviation: "TOR",
    away_abbreviation: "CHI",
    home_wins: 27,
    home_losses: 19,
    away_wins: 22,
    away_losses: 25,
    home_score: 73,
    away_score: 70,
    status: "Q3 3:55",
    home_win_prob: 58,
    away_win_prob: 42,
  }),
  mockGame({
    game_id: "mock-009",
    home_team: "Pelicans",
    away_team: "Thunder",
    home_city: "New Orleans",
    away_city: "Oklahoma City",
    home_abbreviation: "NOP",
    away_abbreviation: "OKC",
    home_wins: 11,
    home_losses: 36,
    away_wins: 37,
    away_losses: 9,
    home_score: 98,
    away_score: 102,
    status: "Final",
    home_win_prob: 38,
    away_win_prob: 62,
  }),
];
