export const mockGames = [
  {
    game_id: "mock-001",
    home_team: "Lakers",
    away_team: "Warriors",
    home_score: 145,
    away_score: 108,
    home_record: "28-16",
    away_record: "26-18",
    quarter: "Final",
    clock: "00:00",
    hitChance: 0.75,
  },
  {
    game_id: "mock-002",
    home_team: "Celtics",
    away_team: "Heat",
    home_score: 101,
    away_score: 99,
    home_record: "30-15",
    away_record: "24-21",
    quarter: "Q4",
    clock: "2:31",
    hitChance: 0.68,
  },
  {
    game_id: "mock-003",
    home_team: "Bucks",
    away_team: "76ers",
    home_score: 87,
    away_score: 92,
    home_record: "18-25",
    away_record: "27-19",
    quarter: "Q3",
    clock: "7:44",
    hitChance: 0.55,
  },
  {
    game_id: "mock-004",
    home_team: "Nuggets",
    away_team: "Suns",
    home_score: 55,
    away_score: 58,
    home_record: "30-15",
    away_record: "27-18",
    quarter: "Halftime",
    clock: "00:00",
    hitChance: 0.62,
  },
  {
    game_id: "mock-005",
    home_team: "Knicks",
    away_team: "Nets",
    home_score: 91,
    away_score: 61,
    home_record: "25-20",
    away_record: "12-31",
    quarter: "Q2",
    clock: "1:18",
    hitChance: 0.82,
  },
  {
    game_id: "mock-006",
    home_team: "Mavericks",
    away_team: "Clippers",
    home_score: 120,
    away_score: 117,
    home_record: "26-19",
    away_record: "24-21",
    quarter: "Final",
    clock: "00:00",
    hitChance: 0.71,
  },
  {
    game_id: "mock-007",
    home_team: "Kings",
    away_team: "Grizzlies",
    home_score: 89,
    away_score: 94,
    home_record: "12-34",
    away_record: "18-25",
    quarter: "Q4",
    clock: "9:02",
    hitChance: 0.45,
  },
  {
    game_id: "mock-008",
    home_team: "Raptors",
    away_team: "Bulls",
    home_score: 73,
    away_score: 70,
    home_record: "27-19",
    away_record: "22-25",
    quarter: "Q3",
    clock: "3:55",
    hitChance: 0.58,
  },
  {
    game_id: "mock-009",
    home_team: "Pelicans",
    away_team: "Thunder",
    home_score: 98,
    away_score: 102,
    home_record: "11-36",
    away_record: "37-9",
    quarter: "Final",
    clock: "00:00",
    hitChance: 0.38,
  },
]