export const mockGames = [
  {
    game_id: "mock-001",
    home_team: "Lakers",
    away_team: "Warriors",
    home_abbreviation: "LAL",
    away_abbreviation: "GSW",
    home_score: 145,
    away_score: 108,
    home_record: "28-16",
    away_record: "26-18",
    home_stats: {
      rebounds: 52,
      assists: 30,
      turnovers: 12,
      fg_percentage: 0.48,
      tp_percentage: 0.37
    },
    away_stats: {
      rebounds: 40,
      assists: 25,
      turnovers: 15,
      fg_percentage: 0.42,
      tp_percentage: 0.33
    },
    quarter: "Final",
    clock: "00:00",
    hitChance: 0.75,
  },
  {
    game_id: "mock-002",
    home_team: "Celtics",
    away_team: "Heat",
    home_abbreviation: "BOS",
    away_abbreviation: "MIA",
    home_score: 101,
    away_score: 99,
    home_record: "30-15",
    away_record: "24-21",
    home_stats: {
      rebounds: 48,
      assists: 22,
      turnovers: 14,
      fg_percentage: 0.47,
      tp_percentage: 0.36
    },
    away_stats: {
      rebounds: 44,
      assists: 24,
      turnovers: 13,
      fg_percentage: 0.45,
      tp_percentage: 0.34
    },
    quarter: "Q4",
    clock: "2:31",
    hitChance: 0.68,
  },
  {
    game_id: "mock-003",
    home_team: "Bucks",
    away_team: "76ers",
    home_abbreviation: "MIL",
    away_abbreviation: "PHI",
    home_score: 87,
    away_score: 92,
    home_record: "18-25",
    away_record: "27-19",
    home_stats: {
      rebounds: 50,
      assists: 26,
      turnovers: 11,
      fg_percentage: 0.49,
      tp_percentage: 0.38
    },
    away_stats: {
      rebounds: 46,
      assists: 24,
      turnovers: 12,
      fg_percentage: 0.46,
      tp_percentage: 0.35
    },
    quarter: "Q3",
    clock: "7:44",
    hitChance: 0.55,
  },
  {
    game_id: "mock-004",
    home_team: "Nuggets",
    away_team: "Suns",
    home_abbreviation: "DEN",
    away_abbreviation: "PHX",
    home_score: 55,
    away_score: 58,
    home_record: "30-15",
    away_record: "27-18",
    home_stats: {
      rebounds: 55,
      assists: 28,
      turnovers: 10,
      fg_percentage: 0.52,
      tp_percentage: 0.41
    },
    away_stats: {
      rebounds: 48,
      assists: 27,
      turnovers: 12,
      fg_percentage: 0.50,
      tp_percentage: 0.39
    },
    quarter: "Halftime",
    clock: "00:00",
    hitChance: 0.62,
  },
  {
    game_id: "mock-005",
    home_team: "Knicks",
    away_team: "Nets",
    home_abbreviation: "NYK",
    away_abbreviation: "BKN",
    home_score: 91,
    away_score: 61,
    home_record: "25-20",
    away_record: "12-31",
    home_stats: {
      rebounds: 43,
      assists: 20,
      turnovers: 11,
      fg_percentage: 0.44,
      tp_percentage: 0.33
    },
    away_stats: {
      rebounds: 38,
      assists: 18,
      turnovers: 15,
      fg_percentage: 0.39,
      tp_percentage: 0.31
    },
    quarter: "Q2",
    clock: "1:18",
    hitChance: 0.82,
  },
  {
    game_id: "mock-006",
    home_team: "Mavericks",
    away_team: "Clippers",
    home_abbreviation: "DAL",
    away_abbreviation: "LAC",
    home_score: 120,
    away_score: 117,
    home_record: "26-19",
    away_record: "24-21",
    home_stats: {
      rebounds: 47,
      assists: 29,
      turnovers: 13,
      fg_percentage: 0.48,
      tp_percentage: 0.37
    },
    away_stats: {
      rebounds: 46,
      assists: 25,
      turnovers: 12,
      fg_percentage: 0.47,
      tp_percentage: 0.36
    },
    quarter: "Final",
    clock: "00:00",
    hitChance: 0.71,
  },
  {
    game_id: "mock-007",
    home_team: "Kings",
    away_team: "Grizzlies",
    home_abbreviation: "SAC",
    away_abbreviation: "MEM",
    home_score: 89,
    away_score: 94,
    home_record: "12-34",
    away_record: "18-25",
    home_stats: {
      rebounds: 41,
      assists: 19,
      turnovers: 16,
      fg_percentage: 0.41,
      tp_percentage: 0.29
    },
    away_stats: {
      rebounds: 45,
      assists: 22,
      turnovers: 14,
      fg_percentage: 0.43,
      tp_percentage: 0.32
    },
    quarter: "Q4",
    clock: "9:02",
    hitChance: 0.45,
  },
  {
    game_id: "mock-008",
    home_team: "Raptors",
    away_team: "Bulls",
    home_abbreviation: "TOR",
    away_abbreviation: "CHI",
    home_score: 73,
    away_score: 70,
    home_record: "27-19",
    away_record: "22-25",
    home_stats: {
      rebounds: 44,
      assists: 23,
      turnovers: 12,
      fg_percentage: 0.43,
      tp_percentage: 0.34
    },
    away_stats: {
      rebounds: 42,
      assists: 21,
      turnovers: 13,
      fg_percentage: 0.41,
      tp_percentage: 0.33
    },
    quarter: "Q3",
    clock: "3:55",
    hitChance: 0.58,
  },
  {
    game_id: "mock-009",
    home_team: "Pelicans",
    away_team: "Thunder",
    home_abbreviation: "NO",
    away_abbreviation: "OKC",
    home_score: 98,
    away_score: 102,
    home_record: "11-36",
    away_record: "37-9",
    home_stats: {
      rebounds: 39,
      assists: 18,
      turnovers: 17,
      fg_percentage: 0.40,
      tp_percentage: 0.30
    },
    away_stats: {
      rebounds: 52,
      assists: 28,
      turnovers: 10,
      fg_percentage: 0.51,
      tp_percentage: 0.42
    },
    quarter: "Final",
    clock: "00:00",
    hitChance: 0.38,
  },
]